const menu = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: 'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/51a9c5b156c84977ae50004b5ef622b2/finalFB.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://www.chewboom.com/wp-content/uploads/2018/07/Denny%E2%80%99s-Adds-New-Americas-Diner-Cheeseburger-678x381.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Cup_of_Milo_Dinosaur_June_29%2C_2013.jpg/200px-Cup_of_Milo_Dinosaur_June_29%2C_2013.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/FrenchToast.JPG/220px-FrenchToast.JPG',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Granola%2C_yogurt%2C_fruit._%2816696981528%29.jpg/220px-Granola%2C_yogurt%2C_fruit._%2816696981528%29.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/McD-Bacon-Egg-Cheese-McGriddle.jpg/235px-McD-Bacon-Egg-Cheese-McGriddle.jpg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Quiche.jpg/250px-Quiche.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Pastry-Turnover-Apple.jpg/220px-Pastry-Turnover-Apple.jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Mmm..._sliders_and_deep_fried_hash_browns_%287958927842%29.jpg/220px-Mmm..._sliders_and_deep_fried_hash_browns_%287958927842%29.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;